[[acl]]
arch = "aarch64"
git-tree-sha1 = "4b0f161422bba75a2eff1c42498fc8936a98de73"
libc = "glibc"
os = "linux"

    [[acl.download]]
    sha256 = "1784953e2ce03119badb48e12f96ae435f961abcba6d57a55df0edabb4e1771d"
    url = "https://github.com/JuliaBinaryWrappers/acl_jll.jl/releases/download/acl-v2.2.53+0/acl.v2.2.53.aarch64-linux-gnu.tar.gz"
[[acl]]
arch = "aarch64"
git-tree-sha1 = "fd7079b5232199f065f65986befe68aada8553ad"
libc = "musl"
os = "linux"

    [[acl.download]]
    sha256 = "068616e7f13e3dff2bc4461727bee9e71cf2a8bd196b3cba3dd3a28bdf634ed6"
    url = "https://github.com/JuliaBinaryWrappers/acl_jll.jl/releases/download/acl-v2.2.53+0/acl.v2.2.53.aarch64-linux-musl.tar.gz"
[[acl]]
arch = "armv7l"
git-tree-sha1 = "86ba17b9754c63256070932c684fb422ef12ca65"
libc = "glibc"
os = "linux"

    [[acl.download]]
    sha256 = "9084032210ce1fc862d9453486d5a1f9a5150dbff4b2391a9855316399f9f824"
    url = "https://github.com/JuliaBinaryWrappers/acl_jll.jl/releases/download/acl-v2.2.53+0/acl.v2.2.53.armv7l-linux-gnueabihf.tar.gz"
[[acl]]
arch = "armv7l"
git-tree-sha1 = "05f57ab0da5dfcf42dcaa59d8c24e6dace901ecb"
libc = "musl"
os = "linux"

    [[acl.download]]
    sha256 = "67d9ab4a4788f02c323410257b4361a02cedb80a9a9ce5a62c6276e9cef2b1eb"
    url = "https://github.com/JuliaBinaryWrappers/acl_jll.jl/releases/download/acl-v2.2.53+0/acl.v2.2.53.armv7l-linux-musleabihf.tar.gz"
[[acl]]
arch = "i686"
git-tree-sha1 = "1aab5d8309a1547ae23ab289423247516b067fe7"
libc = "glibc"
os = "linux"

    [[acl.download]]
    sha256 = "8c3d8d477fa11d1e1b1c7fc42153f9ca2bb04a8d24c36bf48496e844b9fa5bb1"
    url = "https://github.com/JuliaBinaryWrappers/acl_jll.jl/releases/download/acl-v2.2.53+0/acl.v2.2.53.i686-linux-gnu.tar.gz"
[[acl]]
arch = "i686"
git-tree-sha1 = "9f610253b6d97ea915ab2f3f55bf130d7a22ea6e"
libc = "musl"
os = "linux"

    [[acl.download]]
    sha256 = "c31e45cfbca675be92372ef183c183bb892f202e6e03b1ced5204e803c9dbbd4"
    url = "https://github.com/JuliaBinaryWrappers/acl_jll.jl/releases/download/acl-v2.2.53+0/acl.v2.2.53.i686-linux-musl.tar.gz"
[[acl]]
arch = "powerpc64le"
git-tree-sha1 = "79f7e8d2ed9043d991b1ce904620d1352d864823"
libc = "glibc"
os = "linux"

    [[acl.download]]
    sha256 = "ee12f23d97edaf63442503353385876a5f850e5fbdb635867fe96d01b3dfcabc"
    url = "https://github.com/JuliaBinaryWrappers/acl_jll.jl/releases/download/acl-v2.2.53+0/acl.v2.2.53.powerpc64le-linux-gnu.tar.gz"
[[acl]]
arch = "x86_64"
git-tree-sha1 = "332c033c8a138b390b0ded8ef91b01ca6ca865f0"
libc = "glibc"
os = "linux"

    [[acl.download]]
    sha256 = "fe0243e4492b19c383e25ae88fb175c01f738ad9618a5fcaa280526debfbd709"
    url = "https://github.com/JuliaBinaryWrappers/acl_jll.jl/releases/download/acl-v2.2.53+0/acl.v2.2.53.x86_64-linux-gnu.tar.gz"
[[acl]]
arch = "x86_64"
git-tree-sha1 = "341416a8147652460b3173a92fb65a52395f9c13"
libc = "musl"
os = "linux"

    [[acl.download]]
    sha256 = "a3cd55a7a139f7fe92c17417a0f81be97c4fca38948e2c04d39b49cea44eac02"
    url = "https://github.com/JuliaBinaryWrappers/acl_jll.jl/releases/download/acl-v2.2.53+0/acl.v2.2.53.x86_64-linux-musl.tar.gz"
