[[acl]]
arch = "aarch64"
git-tree-sha1 = "e1c5cba3a4aa121fd6cfe14741202a4458330ddb"
libc = "glibc"
os = "linux"

    [[acl.download]]
    sha256 = "b666d31d2b02ecf7f005e922cdc11c959a42af0d44b2eb353c74a33b17a09d46"
    url = "https://github.com/JuliaBinaryWrappers/acl_jll.jl/releases/download/acl-v2.3.1+0/acl.v2.3.1.aarch64-linux-gnu.tar.gz"
[[acl]]
arch = "aarch64"
git-tree-sha1 = "7bd9ee67830736083f3952133c0aeb45bf65607a"
libc = "musl"
os = "linux"

    [[acl.download]]
    sha256 = "84d5243cc33fc08a65e96b074cdc51503248f3ec4446b6178ef51a91edcb846f"
    url = "https://github.com/JuliaBinaryWrappers/acl_jll.jl/releases/download/acl-v2.3.1+0/acl.v2.3.1.aarch64-linux-musl.tar.gz"
[[acl]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5d5f892389dc60be0647eddc500403b024ad5a37"
libc = "glibc"
os = "linux"

    [[acl.download]]
    sha256 = "7d10791ce4fd2a4cf7dee0277051a07741f0f8b20711be6a3d80f99c62a19948"
    url = "https://github.com/JuliaBinaryWrappers/acl_jll.jl/releases/download/acl-v2.3.1+0/acl.v2.3.1.armv6l-linux-gnueabihf.tar.gz"
[[acl]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e399e1031787774f1b74e5d77018e8a989c18447"
libc = "musl"
os = "linux"

    [[acl.download]]
    sha256 = "32e28fa1686decb3cd1822d8c56f5435edf5c6f13a0b9df7d04dbf129f018971"
    url = "https://github.com/JuliaBinaryWrappers/acl_jll.jl/releases/download/acl-v2.3.1+0/acl.v2.3.1.armv6l-linux-musleabihf.tar.gz"
[[acl]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6674cb5736f90a3544ba6ffe450e4e66370748ac"
libc = "glibc"
os = "linux"

    [[acl.download]]
    sha256 = "4ee21923bc7ff0f6d4f52d18489f6c9e43e42c1158da43549831963f85376b58"
    url = "https://github.com/JuliaBinaryWrappers/acl_jll.jl/releases/download/acl-v2.3.1+0/acl.v2.3.1.armv7l-linux-gnueabihf.tar.gz"
[[acl]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f3af0167e66ce721ecea2211f9a5831f20f392dd"
libc = "musl"
os = "linux"

    [[acl.download]]
    sha256 = "3dec877214c224e8fa6ba64d55270b134aca4662c1fd757bb1e083c7ae237d28"
    url = "https://github.com/JuliaBinaryWrappers/acl_jll.jl/releases/download/acl-v2.3.1+0/acl.v2.3.1.armv7l-linux-musleabihf.tar.gz"
[[acl]]
arch = "i686"
git-tree-sha1 = "dd5851a40c5d22541ceb4ba40da4dc494e4e36b7"
libc = "glibc"
os = "linux"

    [[acl.download]]
    sha256 = "6da00c319021af770af50da7926cb79a63ab4918cb6c75ecf1d803287f5fadb1"
    url = "https://github.com/JuliaBinaryWrappers/acl_jll.jl/releases/download/acl-v2.3.1+0/acl.v2.3.1.i686-linux-gnu.tar.gz"
[[acl]]
arch = "i686"
git-tree-sha1 = "7f53cc44d3608340578ec6bb9556f4cc08adb3cb"
libc = "musl"
os = "linux"

    [[acl.download]]
    sha256 = "d74aea99947ff8dd202c7a8717c154418bb94726576fc04f5e8f6c43676b6fcb"
    url = "https://github.com/JuliaBinaryWrappers/acl_jll.jl/releases/download/acl-v2.3.1+0/acl.v2.3.1.i686-linux-musl.tar.gz"
[[acl]]
arch = "powerpc64le"
git-tree-sha1 = "a4d7dc82c5b86c99f8c277443ba11fbf6884bb44"
libc = "glibc"
os = "linux"

    [[acl.download]]
    sha256 = "3361a249f9da652f56760d1fdf156c538b34cd58f68786808fc1f5e5e55c9a28"
    url = "https://github.com/JuliaBinaryWrappers/acl_jll.jl/releases/download/acl-v2.3.1+0/acl.v2.3.1.powerpc64le-linux-gnu.tar.gz"
[[acl]]
arch = "x86_64"
git-tree-sha1 = "970123c546e25cf1eb79a7279218b8b120f661d6"
libc = "glibc"
os = "linux"

    [[acl.download]]
    sha256 = "fa977d666f28e729483b8cee82f7449370a7f5e6d5704134c44f166d9ecf1d6d"
    url = "https://github.com/JuliaBinaryWrappers/acl_jll.jl/releases/download/acl-v2.3.1+0/acl.v2.3.1.x86_64-linux-gnu.tar.gz"
[[acl]]
arch = "x86_64"
git-tree-sha1 = "90ffe836d11f38f4604e499924b997a93d50f694"
libc = "musl"
os = "linux"

    [[acl.download]]
    sha256 = "56fa8a5c455b36b86df750603fde1df63b986c9358f2a113732f95e3b09e293b"
    url = "https://github.com/JuliaBinaryWrappers/acl_jll.jl/releases/download/acl-v2.3.1+0/acl.v2.3.1.x86_64-linux-musl.tar.gz"
