[[acl]]
arch = "aarch64"
git-tree-sha1 = "994ed6a7c4cfc2c8bf431292929e1b0783899abb"
libc = "glibc"
os = "linux"

    [[acl.download]]
    sha256 = "a164e36be22de773eeda4015c36fbb66c0db4f0cae9c784a993229f50f9d974f"
    url = "https://github.com/JuliaBinaryWrappers/acl_jll.jl/releases/download/acl-v2.4.0+0/acl.v2.4.0.aarch64-linux-gnu.tar.gz"
[[acl]]
arch = "aarch64"
git-tree-sha1 = "5d62d9b436d2ef28156cdf12e14cb99fcbf2e142"
libc = "musl"
os = "linux"

    [[acl.download]]
    sha256 = "b451319dfc6b57cef4c0675878c7407a9ff1e97ffb24a1e2ddde70520b859390"
    url = "https://github.com/JuliaBinaryWrappers/acl_jll.jl/releases/download/acl-v2.4.0+0/acl.v2.4.0.aarch64-linux-musl.tar.gz"
[[acl]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "936677250b155deffac9976f7bf70a795950cfcc"
libc = "glibc"
os = "linux"

    [[acl.download]]
    sha256 = "c841d9fbc1be842cb95ae0269a433eb6e42d5d26933eb44af6c6467cee7da638"
    url = "https://github.com/JuliaBinaryWrappers/acl_jll.jl/releases/download/acl-v2.4.0+0/acl.v2.4.0.armv6l-linux-gnueabihf.tar.gz"
[[acl]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "85e2c15840f236ef47eeabf7c67baa591d3b67fc"
libc = "musl"
os = "linux"

    [[acl.download]]
    sha256 = "3eb362ca6e18e79f31ca454ead4edc724199c348dd2fe3f1f6434ef76815fa10"
    url = "https://github.com/JuliaBinaryWrappers/acl_jll.jl/releases/download/acl-v2.4.0+0/acl.v2.4.0.armv6l-linux-musleabihf.tar.gz"
[[acl]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f349869e7a6656ef05347eeee95926f92d4c3921"
libc = "glibc"
os = "linux"

    [[acl.download]]
    sha256 = "cab8f16757abc86cb8d7954b4620f40843fd09004b17518145a036186e873bd7"
    url = "https://github.com/JuliaBinaryWrappers/acl_jll.jl/releases/download/acl-v2.4.0+0/acl.v2.4.0.armv7l-linux-gnueabihf.tar.gz"
[[acl]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5883966bb7a4bf94c241797f1d9bf81756ae98c5"
libc = "musl"
os = "linux"

    [[acl.download]]
    sha256 = "fe6bbc59221780e07d7240150b1a7c6773ca1b0483c89f34b49956a198b8acfd"
    url = "https://github.com/JuliaBinaryWrappers/acl_jll.jl/releases/download/acl-v2.4.0+0/acl.v2.4.0.armv7l-linux-musleabihf.tar.gz"
[[acl]]
arch = "i686"
git-tree-sha1 = "45cce46f69301d51e24c02b6e77078203a0236f5"
libc = "glibc"
os = "linux"

    [[acl.download]]
    sha256 = "4ccd82e1aa57282258d2fe44fbb05fc712be48d5836fd0b79a7b45f228f62042"
    url = "https://github.com/JuliaBinaryWrappers/acl_jll.jl/releases/download/acl-v2.4.0+0/acl.v2.4.0.i686-linux-gnu.tar.gz"
[[acl]]
arch = "i686"
git-tree-sha1 = "80032050f75b7045c7acf0a07c30fec5f0643800"
libc = "musl"
os = "linux"

    [[acl.download]]
    sha256 = "cb2fc05e6bc75a7e77781a6732a2b0d05013d716d8af16d3d2b8de839a487679"
    url = "https://github.com/JuliaBinaryWrappers/acl_jll.jl/releases/download/acl-v2.4.0+0/acl.v2.4.0.i686-linux-musl.tar.gz"
[[acl]]
arch = "powerpc64le"
git-tree-sha1 = "cc977a3975cd5b13a249a95bfa72555fd5c32ace"
libc = "glibc"
os = "linux"

    [[acl.download]]
    sha256 = "2d57b0a206a80b52e61f5a1db7137978d6f1aa4422a02b99eb9b340ce7706f2a"
    url = "https://github.com/JuliaBinaryWrappers/acl_jll.jl/releases/download/acl-v2.4.0+0/acl.v2.4.0.powerpc64le-linux-gnu.tar.gz"
[[acl]]
arch = "riscv64"
git-tree-sha1 = "bdf339cae37449876714ff99224bbaeae5b1fb5f"
libc = "glibc"
os = "linux"

    [[acl.download]]
    sha256 = "3eb5aabdf8797791ce569ea92ec3893b82ca65295a637ecc0d03dbee983c1fb6"
    url = "https://github.com/JuliaBinaryWrappers/acl_jll.jl/releases/download/acl-v2.4.0+0/acl.v2.4.0.riscv64-linux-gnu.tar.gz"
[[acl]]
arch = "x86_64"
git-tree-sha1 = "31f99349056b1f6f07ea09ff2505865e5889d8a0"
libc = "glibc"
os = "linux"

    [[acl.download]]
    sha256 = "9181abf02c16165dc24776317ff88e6aa405f42b8cf3071d8d57cf5a50d04991"
    url = "https://github.com/JuliaBinaryWrappers/acl_jll.jl/releases/download/acl-v2.4.0+0/acl.v2.4.0.x86_64-linux-gnu.tar.gz"
[[acl]]
arch = "x86_64"
git-tree-sha1 = "9697043ec8ad84cd527738eee3bae8dbc0c41431"
libc = "musl"
os = "linux"

    [[acl.download]]
    sha256 = "2df04d0930ee09848c7c444e0b24af9de99410ccf8effa0a22f3251e5ccdab04"
    url = "https://github.com/JuliaBinaryWrappers/acl_jll.jl/releases/download/acl-v2.4.0+0/acl.v2.4.0.x86_64-linux-musl.tar.gz"
