[[acl]]
arch = "aarch64"
git-tree-sha1 = "06e3a8eaadcd691d15ab15d3b79e3b53fb649202"
libc = "glibc"
os = "linux"

    [[acl.download]]
    sha256 = "cb2af920a2021ad340a62bade9676bb28292d22b86b71c0de7cbd034f102dac2"
    url = "https://github.com/JuliaBinaryWrappers/acl_jll.jl/releases/download/acl-v2.3.2+0/acl.v2.3.2.aarch64-linux-gnu.tar.gz"
[[acl]]
arch = "aarch64"
git-tree-sha1 = "fff1506d6ddb4cc042c6f9d3d02806adb5cbaae4"
libc = "musl"
os = "linux"

    [[acl.download]]
    sha256 = "467b57391041f7d8c1800a2c05fa1db966c879b9bf443fa0c90ce0a4a44842bf"
    url = "https://github.com/JuliaBinaryWrappers/acl_jll.jl/releases/download/acl-v2.3.2+0/acl.v2.3.2.aarch64-linux-musl.tar.gz"
[[acl]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b758522741e871143199a53d1e4ee29a65d0073a"
libc = "glibc"
os = "linux"

    [[acl.download]]
    sha256 = "f6b4b7c62b930a5bc35bece30cfef2bac87852acf68986bfaf35fd8f741f811c"
    url = "https://github.com/JuliaBinaryWrappers/acl_jll.jl/releases/download/acl-v2.3.2+0/acl.v2.3.2.armv6l-linux-gnueabihf.tar.gz"
[[acl]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f377fba0eb51ad646bf9d6adfdfc0725625b9ef8"
libc = "musl"
os = "linux"

    [[acl.download]]
    sha256 = "6dc1d5ad20a56d3442df049ae643a92b19de030e187aef59b0c54a95c6b6eb6e"
    url = "https://github.com/JuliaBinaryWrappers/acl_jll.jl/releases/download/acl-v2.3.2+0/acl.v2.3.2.armv6l-linux-musleabihf.tar.gz"
[[acl]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7147702cb0fcc65fe26ea74f186e2a59e8d0c415"
libc = "glibc"
os = "linux"

    [[acl.download]]
    sha256 = "612a69b6f3f94c999d8f6e66b2ec3e1f85a1da9fecbdac716f9c19abee3138d3"
    url = "https://github.com/JuliaBinaryWrappers/acl_jll.jl/releases/download/acl-v2.3.2+0/acl.v2.3.2.armv7l-linux-gnueabihf.tar.gz"
[[acl]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2ef2036d9136f33ab91fec70fe8c361bfa47346a"
libc = "musl"
os = "linux"

    [[acl.download]]
    sha256 = "6a77353e38e4a6b5c0d8cad172cd6b2c1eb3bffedd561a129b05e749eee3d35c"
    url = "https://github.com/JuliaBinaryWrappers/acl_jll.jl/releases/download/acl-v2.3.2+0/acl.v2.3.2.armv7l-linux-musleabihf.tar.gz"
[[acl]]
arch = "i686"
git-tree-sha1 = "b62891bcf1b9a91fdc42f091e9a436b6f3c49829"
libc = "glibc"
os = "linux"

    [[acl.download]]
    sha256 = "4d9eb5dbff39e5a8d09e81d29dd91b52b737d34991ea280fd231c2cd6fe7fb60"
    url = "https://github.com/JuliaBinaryWrappers/acl_jll.jl/releases/download/acl-v2.3.2+0/acl.v2.3.2.i686-linux-gnu.tar.gz"
[[acl]]
arch = "i686"
git-tree-sha1 = "3073c9dccf7aa0689894884f9e6a044abb05b90d"
libc = "musl"
os = "linux"

    [[acl.download]]
    sha256 = "a4f623693ce1dcd83491f3278c2882901ab8c73c83f8cd93404e5876e576332a"
    url = "https://github.com/JuliaBinaryWrappers/acl_jll.jl/releases/download/acl-v2.3.2+0/acl.v2.3.2.i686-linux-musl.tar.gz"
[[acl]]
arch = "powerpc64le"
git-tree-sha1 = "878c99a38709ea5388f50bfc1182dfe586f784d8"
libc = "glibc"
os = "linux"

    [[acl.download]]
    sha256 = "ad136ff089bb2fb5804db2bdccf6cc67dd27d0cb5ccf1a89a8e27fe900f7ee70"
    url = "https://github.com/JuliaBinaryWrappers/acl_jll.jl/releases/download/acl-v2.3.2+0/acl.v2.3.2.powerpc64le-linux-gnu.tar.gz"
[[acl]]
arch = "x86_64"
git-tree-sha1 = "e947e53742f7750e5c8299c7d07a4b755589e653"
libc = "glibc"
os = "linux"

    [[acl.download]]
    sha256 = "418ffdcbcc7398d4f99a7c5ec21c7f295596672c58a6275378ac63af8e0fbd6a"
    url = "https://github.com/JuliaBinaryWrappers/acl_jll.jl/releases/download/acl-v2.3.2+0/acl.v2.3.2.x86_64-linux-gnu.tar.gz"
[[acl]]
arch = "x86_64"
git-tree-sha1 = "5f16d07736e6bdc2133c0735cca427697f25a32c"
libc = "musl"
os = "linux"

    [[acl.download]]
    sha256 = "e340bf6cbc8addb0039fd91109efe9f1c3ceb2dc747cb3b089a28956fd43a514"
    url = "https://github.com/JuliaBinaryWrappers/acl_jll.jl/releases/download/acl-v2.3.2+0/acl.v2.3.2.x86_64-linux-musl.tar.gz"
