[[acl]]
arch = "aarch64"
git-tree-sha1 = "fe6cf07870fea0c2ce5242b29e6eed4043b51407"
libc = "glibc"
os = "linux"

    [[acl.download]]
    sha256 = "c6c1870f795aaaf18f6fe9f555e89b3ce5eaa6d210d1607b8801443c5c6818d1"
    url = "https://github.com/JuliaBinaryWrappers/acl_jll.jl/releases/download/acl-v2.3.3+0/acl.v2.3.3.aarch64-linux-gnu.tar.gz"
[[acl]]
arch = "aarch64"
git-tree-sha1 = "c48a2a8104a29190b1059384a3ce09f07d48c8ce"
libc = "musl"
os = "linux"

    [[acl.download]]
    sha256 = "2252c781c843505760154ce3056a85cc586c662e0c687d0b63a1964d014e02c7"
    url = "https://github.com/JuliaBinaryWrappers/acl_jll.jl/releases/download/acl-v2.3.3+0/acl.v2.3.3.aarch64-linux-musl.tar.gz"
[[acl]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "817474533227797685f26c2821cd8e9cfe4dabfd"
libc = "glibc"
os = "linux"

    [[acl.download]]
    sha256 = "f164f4d58acb8af915af93111c13376f6f1535accf2e9de3b01683c20aea0c8e"
    url = "https://github.com/JuliaBinaryWrappers/acl_jll.jl/releases/download/acl-v2.3.3+0/acl.v2.3.3.armv6l-linux-gnueabihf.tar.gz"
[[acl]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a041611946aec78b522fe89fe9db80962054a376"
libc = "musl"
os = "linux"

    [[acl.download]]
    sha256 = "82ab103aa317f23bf5c4ec23fafe4372639f79f3b63975697b527019f49c1ce4"
    url = "https://github.com/JuliaBinaryWrappers/acl_jll.jl/releases/download/acl-v2.3.3+0/acl.v2.3.3.armv6l-linux-musleabihf.tar.gz"
[[acl]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fc175941029eca66fc9f115ca13e2a80b9d0b198"
libc = "glibc"
os = "linux"

    [[acl.download]]
    sha256 = "58a3ab8c81a3bfd665aaf83ce62e76088d30cf8c13f9b34c3536d8ba20029469"
    url = "https://github.com/JuliaBinaryWrappers/acl_jll.jl/releases/download/acl-v2.3.3+0/acl.v2.3.3.armv7l-linux-gnueabihf.tar.gz"
[[acl]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1dd4b724aff8e029b8164dc9ba067650d3f412c0"
libc = "musl"
os = "linux"

    [[acl.download]]
    sha256 = "38d600f15fd3a83c99746c147ab7ed98bec34dbe0783e2e278f4061087b5f227"
    url = "https://github.com/JuliaBinaryWrappers/acl_jll.jl/releases/download/acl-v2.3.3+0/acl.v2.3.3.armv7l-linux-musleabihf.tar.gz"
[[acl]]
arch = "i686"
git-tree-sha1 = "c455d2d24ae112214b2524d225efd6d8d699d52d"
libc = "glibc"
os = "linux"

    [[acl.download]]
    sha256 = "04ed2901f819b4b1a75067cf1716e77f1760cfc7ff4e62d01db3011651260fea"
    url = "https://github.com/JuliaBinaryWrappers/acl_jll.jl/releases/download/acl-v2.3.3+0/acl.v2.3.3.i686-linux-gnu.tar.gz"
[[acl]]
arch = "i686"
git-tree-sha1 = "52d12afd317aff2c60dd1660a36b030c4e6bdd7d"
libc = "musl"
os = "linux"

    [[acl.download]]
    sha256 = "41fbcbeb4d63c01514c827a607d34f9e9e4a7c9764b63b94d15c791e3ab0ed04"
    url = "https://github.com/JuliaBinaryWrappers/acl_jll.jl/releases/download/acl-v2.3.3+0/acl.v2.3.3.i686-linux-musl.tar.gz"
[[acl]]
arch = "powerpc64le"
git-tree-sha1 = "8bf454d9a7703f9e2f6dd8fe2b2ab4335d911fcd"
libc = "glibc"
os = "linux"

    [[acl.download]]
    sha256 = "c69f62f04b68ad3494b5fb70aa5e6ff767855bab6e70ecaffe83506a4922d1fc"
    url = "https://github.com/JuliaBinaryWrappers/acl_jll.jl/releases/download/acl-v2.3.3+0/acl.v2.3.3.powerpc64le-linux-gnu.tar.gz"
[[acl]]
arch = "riscv64"
git-tree-sha1 = "cf0822d4585a27dbd5b1c0c436b2dfefdf87d425"
libc = "glibc"
os = "linux"

    [[acl.download]]
    sha256 = "5ad00efa501dc23ae330d9663812fd4c366a235bc73bafef87298bd179f56566"
    url = "https://github.com/JuliaBinaryWrappers/acl_jll.jl/releases/download/acl-v2.3.3+0/acl.v2.3.3.riscv64-linux-gnu.tar.gz"
[[acl]]
arch = "x86_64"
git-tree-sha1 = "65943eff329758c84076a8734f3364ec761d6975"
libc = "glibc"
os = "linux"

    [[acl.download]]
    sha256 = "89b037f4abd9e036f0025685bec0926b4093c8149c3f2e61d64c9fa5bf90f8d4"
    url = "https://github.com/JuliaBinaryWrappers/acl_jll.jl/releases/download/acl-v2.3.3+0/acl.v2.3.3.x86_64-linux-gnu.tar.gz"
[[acl]]
arch = "x86_64"
git-tree-sha1 = "c8cb7ac92635905336dc8864c46559dc66d63eb4"
libc = "musl"
os = "linux"

    [[acl.download]]
    sha256 = "c5930944ce9d90c58bb78947e164a85256de33cc6d7456270950ec0bd6f81af1"
    url = "https://github.com/JuliaBinaryWrappers/acl_jll.jl/releases/download/acl-v2.3.3+0/acl.v2.3.3.x86_64-linux-musl.tar.gz"
